# Deloppgave 3: Vitenskapsfilosofi

<!-- Part 3: Philosophy of science -->

## Arbeidskrav i vitenskapsteori

### Falsifikasjonisme

Med falsifiserbarhet mener ikke Popper nødvendigvis at noe er falskt, men mer det at teorien kommer med noen punkter som kan bli testet opp mot erfaring. Disse punktene som kan bli testet opp mot erfaring kan vise seg og være feil, og dersom dette skjer vil teorien være motbevist eller forfalsket. Med andre ord vil en falsifiserbar teori være en som man kanskje oppdager at kan være falsk, og den vil derfor ikke passe til alle erfaringer (Okasha, 2016, s. 13).

Okasha skriver videre i kapittelet at det at Popper prøver å avgrense vitenskap fra pseudovitenskap er ganske realistisk. Ifølge Popper ville en god vitenskapelig teori bety at den er falsifiserbar, altså det skal være mulig å bevise at den er gal eller uholdbar, noe som igjen betyr at den er det motsatte av å kunne verifiseres. Ifølge Popper er det en tydelig linje mellom vitenskapelige og pseudovitenskapelige teorier (falsifiserbare og ufalsifiserbare teorier), og de vitenskapelige teoriene kan ikke bli bekreftet, de kan kun bli falsifisert (Okasha, 2016, s. 13-14). Okasha mener at det absolutt er noe mistenkelig med en teori som kan endres slik at den passer med alle empiriske data (Okasha, 2016, s. 15).

Andre vitenskapsfilosofer mener at vi ikke trenger å svare på spørsmålet omhandlende om et spørsmål kan falsifiseres eller ei. Dette grunnet at vitenskap er en heterogen aktivitet, og som innehar et bredt spekter av forskjellige disipliner og teorier. I kapittelet er det brukt et spill som et eksempel, men kort fortalt menes det at det er vanskelig å si om det er et fast sett med funksjoner som definerer «vitenskap». Eksempelet i boken går på spill. Det kan sees på litt på samme måten. Det finnes mange typer spill, men mange av de sammen funksjonene, men likevel noen ulike funksjoner, for at spillene ikke skal være like, det samme kan det være i vitenskapen også. En bestemt disiplin mangler noen av funksjonene, men kan likevel være en viktig del av vitenskapen. Dersom dette er tilfelle vil det være tvilsomt å kunne finne ett enkelt kriterium for å kunne skille vitenskap fra pseudovitenskap (Okasha, 2016, s. 16-17).

Egne tanker rundt dette med falsifiserbarhet er at jeg er mer enig med de andre vitenskapsfilosofene. Det er vanskelig å kunne gi ett spesifikt kriterium som skal gjelde for et så stort og bredt fagområde, som det vitenskapen er. Jeg er enig med Popper om at det burde være mulig å så tvil til ulike teorier, men at det ikke er en vitenskapelig teori dersom den ikke er falsifiserbar virker til å være litt i overkant strengt. Mye av årsaken til dette er at det er vanskelig å finne noe som kan passe for alle typene vitenskap. Jeg er også enig i at en teori kan være ødelagt til en viss grad dersom den motbevises, men det er vanskelig å vite hvor man skal sette denne grensen.

### HD-metoden og abduksjon

HD-metoden er en forkortelse for hypotetisk deduktiv metode. Denne metoden har en struktur for å bekrefte vitenskapelige argumenter gjennom positive resultater fra de deduktive konsekvensene av teorien (Hempel, 1966). Strukturen på et bekreftende vitenskapelig argument ifølge HD-metoden er delt inn i fire trinn. 1. Formulere teori/hypotese 2. Empiriske konsekvenser fra hypotesen/teorien med deduksjon 3. Test de empiriske konsekvensene i observasjon eller eksperiment 4. Sanne empiriske konsekvenser vil si at det til en viss grad bekreftet hypotese/teori

Som man kan se over starter det med én eller flere ulike hypoteser/teorier. I trinn to vil man se på informasjon som er kommet frem fra hypotesen/teorien, og dette gjøres med deduksjon. Deduksjon er en måte man kan oppnå kunnskap på, uten at det er nødvendig med observasjoner fra virkeligheten, bygger i hovedsak på logikk. I trinn tre vil disse empiriske konsekvensene fra trinn to, altså informasjonen testes med observasjon eller eksperiment. I trinn fire ser man om hypotesen/teorien bekreftes (induktivt) til en viss grad. Dette skjer dersom de empiriske konsekvensene viser seg å være riktige (Dellsén, 2022, s. 3-8).

Et eksempel på en hypotese/teori er om «gjør trening på et treningssenter slik at folk ser muskuløse og «bulkete» ut?» Et deduktivt argument vil da være at siden Dwayne Johnson trener på treningssenter, og mannen i gata er på et treningssenter, vil da denne mannen bli like muskuløs som Dwayne Johnson. Fra trinn tre vil denne hypotesen/teorien testes. Det kan da testes ved å få en på treningssenteret til å trene over en gitt periode uten og endre på noen andre vaner, og se om denne personen da ser ut som Dwayne Johnson etter endt intervensjon. Dersom denne personen faktisk da gjør det etter endt intervensjon, noe hen trolig ikke vil, da det er mer enn litt trening som skal til for å endre kroppen i større grad, vil da hypotesen/teorien til en viss grad bekreftes/motbevises, dersom det motbevises må man prøve en annen hypotese. Personene som har ledet forsøket vil kanskje ha observert andre ting, som for eksempel kostholdet til Dwayne Johnson. Da kan det være aktuelt å prøve og endre kosthold samtidig som man opprettholder treningen over en lenger periode, og se om dette har hatt en større effekt på vedkommende enn kun trening alene.

#### Hempels HD-metode vs. vitenskapelig bekreftelse ifølge abduksjon

Abduksjon er også kjent som «slutning til den beste forklaringen» (Dellsén, 2022, s. 19). Vitenskapelig bekreftelse ifølge abduksjon trenger ikke å ha premisser som innebærer konklusjonen, men abduksjon krever at teorien forklarer dataen bedre enn de andre tilgjengelige alternative teoriene -- altså må man i abduksjon sammenligne ulike teorier som er relevante for å kunne forklare samme fenomen (Dellsén, 2022, s. 21). Ser man på eksempelet i kapittel 2, i boken til Okasha (2016), om osten, musen og hushjelpen, ser man at det er ikke slik at osten må ha blitt spist av musen, da det like gjerne kan ha vært hushjelpen, men det er mer naturlig at det er musen som har gjort dette. Dette fordi den er kjent for å spise ost dersom den får tilgang til det, og at sannsynligheten for at en hushjelp går rundt og stjeler ost er veldig liten. Konklusjonen om at det er musen som har spist osten gir en bedre forklaring på dataene enn de andre alternativene. Ifølge abduksjon trenger man altså ikke være skråsikker på at musehypotesen er sann, da den ser ganske plausibel ut; har den beste måten å gjøre rede for de tilgjengelige dataene på (Okasha, 2016, s. 29-30).

HD-metoden og abduksjon er på mange områder like. Begge handler om å dedusere data til teorien, som igjen fører til en form for bekreftelse, men hovedoppgaven til abduksjonen er å kunne løse problemene i den vanlige HD-metoden, og dette gjøres ved å se på flere ulike teorier, og se hvilke som mulig kunne forklart samme fenomen, men på en best mulig måte (Dellsén, 2022, s. 19).

### Replikasjonskrisen

Alexander Bird (2018) mener at forklaringen til at mange resultatet i noen vitenskaper ikke kan repliseres er at hypotesene til disse resultatene ble foreslått på bakgrunn av resultatene fra tidligere observasjonsstudier, eller til og med av usystematiske observasjoner. Det er helt ok måter å skaffe hypoteser på, men det er ikke midler som skaper hypoteser med en høy sannsynlighet for sannhet. Hypotesene er bygget på tidligere funn fremfor å være forankret i vitenskapelig teori. Det at man sitter med bakgrunnsinformasjon er det rimelig å anta at det vil ha en slik effekt, men denne infoen gjør det absolutt ikke sannsynlig at det vil ha en slik effekt (Bird, 2018, s.975-976). Klinisk medisin og psykologi, da spesielt sosialpsykologi, står i sterk kontrast til for eksempel fysikk på to måter -- og i fysikk kan tester ofte repliseres. Vår forståelse av fysiologi og patologi blir stadig større og bedre, men de aktuelle biologiske systemene er likevel så komplekse at den kunnskapen vi innehar forblir ufullstendig. Hypotesene som vurderes i klinisk medisin er også verken mer eller mindre direkte konsekvenser av underliggende grunnleggende teorier. De er for eksempel hypoteser om virkningen av et medikament på pasienter, og de står derfor i en viss avstand fra den underliggende teorien. For det andre er det eksperimentelle beviset for den underliggende teorien også generelt mye svakere (Bird, 2018, s.976). Det som viser seg å være grunnen til at mange resultater ikke kan repliseres er grunnet basefrekvensfeilen. Basefrekvensfeilen består av to former for feil -- akseptere en teori som ikke er sann eller avvise en teori som kan være sann. Basefrekvensfeilen er en feil som oppstår når man trekker en slutning om sannsynligheten for en bestemt forekomst av et generelt fenomen. Forskeren vil i dette tilfellet fokusere utelukkende på en observasjon, og overse andre observasjoner som også kan ha en innvirkning på endelig resultat. Et eksempel som Bird bruker for forklaring på basekfrekvensfeilen og replikasjonskrisen er et fly med passasjerer, hvor passasjerene blir undersøkt for å være terrorister, og denne testen viser seg å være 95% riktig. I dette eksempelet vil det si at av 100 personer, er det. 95 som ikke er terrorister, mens 5 som vil være det. I verste fall vil det være slik at dersom én person ikke består testen, vil hen bli sett på som en terrorist. Dette så Bird på som tullete, og at dersom denne testen blir trodd, vil det være en usann teori som blir akseptert (Bird, 2018)

Bird viser også i artikkelen sin til Nature-undersøkelsen. Her rapporterte «60% av respondentene at press for å publisere og selektiv rapportering spilte en stor rolle i krisen rundt mislykkede replikasjoner. Mer enn 50% refererte også til utilstrekkelig replikering i laboratoriet, dårlig tilsyn eller lav statistisk kraft» (Bird, 2018, s. 978).

Bird sin forklaring til replikasjonskrisen sammenlignet med andre forklaringer til replikasjonskrisen virker å være godt støttet, ved hjelp av utregninger og lignende. Det er likevel vanskelig å si hvem som har mer rett enn andre. For å kunne konkludere med hvem som har rett må man gå grundig til verks, og undersøke hvorfor ulike studier har mislykkede replikasjonsforsøk. Da må man se etter tegn på skjevhet, dårlig research og forfalskning. Slik jeg tolker det virker Bird ganske sikker på at hans egne argumenter og forklaringer er det som gir mest styrke rundt forklaringen til replikasjonskrisen.

## Litteraturliste

Bird, A. (2018). Understanding the Replication Crisis as a Base Rate Fallacy. *The British Journal for the Philosophy of Science, 72*(4), 965-993. DOI: 10.1093/bjps/axy051

Dellsén, F. (14. oktober.2022). *Abduksjon og sannsynlighet*

Hempel, C. G. (1966). Scientific inquiry: Invention and Test. *Philosophy of natural science* (s. 3-18). Prentice Hall

Okasha, S. (2016). *Philosophy of science: a very short introduction* (2. utgave). Oxford University Press

Popper, K. R. (1969). Science: Conjectures and Refutations. *Conjectures and refutations: the growth of scientific knowledge* (3. utgave) (s. 33-39). Routledge and Kegan Paul
